// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynhzlnxbwiyrimrovfov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluaHpsbnhid2l5cmltcm92Zm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzMyNDQsImV4cCI6MjA3NDY0OTI0NH0.-8ih_f2fZL-do2MONdhIVAxe3LhQ3lgKV80XTKj3lug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});